Fix up the build failure due to unused function chooseCore()
This commit resolves the following build failure:

src/Arachne.h:460:1: error: ‘int Arachne::chooseCore(const
Arachne::CorePolicy::CoreList&)’ defined but not used
[-Werror=unused-function]
 chooseCore(const CorePolicy::CoreList& coreList) {
 ^~~~~~~~~~

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>