Fix build failure due to falling through the default case in switch statement
error: this statement may fall through [-Werror=implicit-fallthrough=]
                 coreArbiterSocketPath = optionArgument;
                 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
src/Arachne.cc:938:13: note: here
             case UNRECOGNIZED:
             ^~~~

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>